### ISSUE TITLE
[bug]: Cards are not properly aligned with the container body.

### ISSUE THREAD

**Issue by execrc** [apu52/HotstarClone#3]
# Card containers are not properly aligned with the body. They have taken different margins from the left and right sides of the body.

## Steps to Reproduce: 
- Go to the Home Page
- Scroll down to the landing page 
- View results from popular shows and new release containers

### Screenshot

![image](https://github.com/apu52/HotstarClone/assets/129402570/08f25653-9936-41e2-89d0-f031e2102b35)

## Expected Result
- :1st_place_medal:  The card container should have equal margins on the left and right sides of the body.

**Comment by 5h0ov** [comment]
Great! You can start working on it! @mnamesujit
